version: '3'
services:
  neo4j:
    image: neo4j:4.2.3
    container_name: neo4j
    ports: 
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
    environment: 
      - NEO4J_AUTH=none

  flask:
    image: 21121/humain:latest
    container_name: flask
    ports: 
    - 5000:5000
    environment:
    - NEO4J_HOST=localhost
    - NEO4J_PORT=7687
    - NEO4J_USERNAME=neo4j
    - NEO4J_PASSWORD=abiss
    - NEO4J_DATABASE_NAME=powerplant
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana_data: