version: '3'
services:
  flask:
    image: 21121/humain:latest
    container_name: flask
    ports: 
    - 5000:5000
    environment:
    - MY_HOST=host.docker.internal
    - MY_PORT=7687
    - MY_USERNAME=neo4j
    - MY_PASSWORD=test
    - DATABASE_NAME=powerplant
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana_data: